name: Generate PI image

on:
  workflow_dispatch:

jobs:
  pi-gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PRIVATE_ACCESS_TOKEN}}

      - uses: usimd/pi-gen-action@v1.10.0
        id: build
        with:
          image-name: DFU
          increase-runner-disk-size: true
          pi-gen-version: 2024-07-04-raspios-bookworm-arm64
          stage-list: stage0 stage1 stage2 ./stage-rndis ./stage-sql ./stage-developpement
          docker-opts: --env SSH_PRIVATE_KEY=${{ secrets.SSH_PRIVATE_KEY }}
      - name: Show disk usage
        if: always()
        run: df -h
      - uses: actions/upload-artifact@v4
        with:
          name: pi-gen-image
          path: ${{ steps.build.outputs.image-path }}
