name: Windows Share Integration Test

on:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: windows-2025

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create directory and test file
        shell: pwsh
        run: |
          # Create the abatteuse directory if it doesn't exist
          New-Item -ItemType Directory -Path 'C:\abatteuse' -Force | Out-Null

          # Create a test hello-world file
          Set-Content -Path 'C:\abatteuse\hello-world.txt' -Value 'Hello World'

      - name: Create Windows share
        shell: pwsh
        run: |
          # Install the SMBShare module if not available (on some images it might be present by default)
          if (!(Get-Module -ListAvailable -Name SmbShare)) {
            Install-WindowsFeature -Name FS-SMB1
          }

          # Create a share named 'abatteuse' pointing to C:\abatteuse
          # This grants FULL access to Guest (assuming the Guest account is enabled)
          New-SmbShare -Name "abatteuse" -Path "C:\abatteuse" -FullAccess "Guest" -Confirm:$false

      - name: Confirm share creation
        shell: pwsh
        run: |
          Get-SmbShare | Where-Object { $_.Name -eq "abatteuse" }
          
      - name: Switch to Linux containers mode
        run: |
          & 'C:\Program Files\Docker\Docker\DockerCli.exe' -SwitchLinuxEngine
        shell: powershell

      - name: Check Docker info
        run: docker info

      - name: Create custom Docker network (if supported)
        shell: pwsh
        run: |
          # Attempt to create a Docker network with a specific subnet
          docker network create --driver nat --subnet=10.0.0.0/24 integration_test_net

      - name: Run Docker container on custom network
        shell: pwsh
        run: |
          # Get the current directory (Windows syntax)
          $CURRENT_DIR = (Get-Location).Path

          # Ensure the path uses Windows-style backslashes (`\`)
          $CURRENT_DIR = $CURRENT_DIR -replace "/", "\"  

          # Start an Ubuntu container in the background, assigned IP 10.0.0.2
          docker run -d --name ubuntu_test `
            --network integration_test_net `
            --ip 10.0.0.2 `
            --hostname ubuntu_test `
            -v "${CURRENT_DIR}:/rasp-pi" `
            ubuntu:latest sh -c "sleep infinity"

          # Update and install cifs-utils (for mounting Samba/SMB shares)
          docker exec ubuntu_test apt-get update
          docker exec ubuntu_test apt-get install -y cifs-utils nmap

          # Now attempt to mount the Windows share from the container
          docker exec ubuntu_test /rasp-pi/testing/windows-share-integration.sh
