name: Windows Share Integration Test

on:
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: windows-2025

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Create directory and test file
        shell: pwsh
        run: |
          # Create the abatteuse directory if it doesn't exist
          New-Item -ItemType Directory -Path 'C:\abatteuse' -Force | Out-Null

          # Create a test hello-world file
          Set-Content -Path 'C:\abatteuse\hello-world.txt' -Value 'Hello World'

      - name: Create Windows share
        shell: pwsh
        run: |
          # Install the SMBShare module if not available (on some images it might be present by default)
          if (!(Get-Module -ListAvailable -Name SmbShare)) {
            Install-WindowsFeature -Name FS-SMB1
          }

          # Create a share named 'abatteuse' pointing to C:\abatteuse
          # This grants FULL access to Guest (assuming the Guest account is enabled)
          New-SmbShare -Name "abatteuse" -Path "C:\abatteuse" -FullAccess "Guest" -Confirm:$false

      - name: Confirm share creation
        shell: pwsh
        run: |
          Get-SmbShare | Where-Object { $_.Name -eq "abatteuse" }

      - name: Set up WSL2
        uses: vedantmgoyal9/setup-wsl2@v1.1.0
        with:
          distro: Ubuntu

      - name: Update package lists
        run: sudo apt-get update
        shell: wsl-run {0}

      - name: Install packages
        run: sudo apt-get install -y cifs-utils nmap
        shell: wsl-run {0}

      - name: Create alias for host
        run: echo "$(grep nameserver /etc/resolv.conf | awk '{print $2}') windows-host" | sudo tee -a /etc/hosts
        shell: wsl-run {0}
      
      - name: Run mount script
        run: ./testing/windows-share-integration.sh
        shell: wsl-run {0}
